# Generated by Django 6.0.3 on 2026-04-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=102.1, max_digits=12),
            preserve_default=False,
        ),
    ]
