# Generated by Django 6.0.3 on 2026-04-11 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='description',
            new_name='comment',
        ),
    ]
