# Generated by Django 6.0.3 on 2026-04-11 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_review_created_at_review_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='date',
        ),
    ]
