# Generated by Django 6.0.3 on 2026-04-14 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_review_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
